name : deployment

on:
    push:
      branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: setup go tool
        run : scripts/buildprod.sh

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true  

      - name: Build and push Docker image to Artifact Registry
        run: gcloud builds submit --project notely-448816 --tag us-central1-docker.pkg.dev/notely-448816/notely-ar-repo/notely:latest .